export enum ActionType {
  SEARCH_INVOICES = "SEARCH_INVOICES",
  SEARCH_INVOICES_SUCCESS = "SEARCH_INVOICES_SUCCESS",
  SEARCH_INVOICES_ERROR = "SEARCH_INVOICES_ERROR",
  CREATE_INVOICE_DRAFT = "CREATE_INVOICE_DRAFT",
  CREATE_INVOICE_SEND = "CREATE_INVOICE_SEND",
  GET_INVOICE_BY_ID = "GET_INVOICE_BY_ID",
}
